apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: apache/spark:3.5.1
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.5.1.jar"
  sparkVersion: "3.5.1"
 
  restartPolicy:
    type: Never
 
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark
    labels:
      version: v3.5.1
 
  executor:
    cores: 1
    memory: 512m
    instances: 2
    serviceAccount: spark
    labels:
      version: v3.5.1
